language: minimal
group: edge
dist: focal

services:
  - docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

install:
  - pip install pytest

script:
  - pytest theDoctor/test/test_app.py.py

after_success:
  - cd theDoctor
  - docker build -t $DOCKER_USERNAME/zenity .

deploy:
  provider: script
  script: docker push $DOCKER_USERNAME/zenity
  on:
    branch: main
