language: minimal

services:
  - docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - cd theDoctor
  - docker build -t $DOCKER_USERNAME/zenity .

deploy:
  provider: script
  script: docker push $DOCKER_USERNAME/zenity
  on:
    branch: main
